import re
from oss_ar.sssalud import ObrasSocialesSSS


def read_afip_select_html(html_path):
    with open(html_path, 'r', encoding='utf-8') as file:
        html_content = file.read()

    results = []

    # detect id and text from each line in html_content like
    # <option value="000000">000000 - Sin Obra Social</option>
    for line in html_content.split('\n'):
        match = re.search(r'<option value="(.+?)">(.+?)</option>', line)
        if match:
            id = match.group(1)
            text = match.group(2)
            results.append({'id': id, 'text': text})

    return results


def compare_afip_data():
    # Get AFIP data
    html_path = 'oss_ar/afip/data/lista-oss-afip-empleados-2024-11.html'
    options_data = read_afip_select_html(html_path)

    # Get OSS data to compare
    s = ObrasSocialesSSS()
    data = s.process_database()

    # Afip usa 6 digitos completando con cetos adelante hasta 6 caracteres
    # Nuestra libreria tiene lo numeros. Neceistamo corregir para comparar

    encontrados = []
    no_encontrados = []
    for option in options_data:
        afip_id = option['id']
        if afip_id in ['-1', '000000']:
            continue
        oss_id = afip_id.lstrip('0')
        oss = data.get(oss_id, {})
        if not oss:
            print(f'{oss_id} No encontrado en nuestra base de datos\n\t{option["text"]}')
            no_encontrados.append(afip_id)
            continue
        oss_tipos = oss['tipos']
        clean_afip_name = option["text"].replace(f'{option["id"]} - ', '')
        print(f'{afip_id} Encrontrado. Tipos: {oss_tipos}\n\tNames:\n\t{clean_afip_name}\n\t{oss["denominacion"]}')
        encontrados.append(afip_id)

    print(f'Total: {len(options_data)}, encontrados = {len(encontrados)}, no encontrados {len(no_encontrados)}')


"""
Diferencias Nov 2024

Total: 300, encontrados = 296, no encontrados 2 (hay 2 ignorados)
117603 No encontrado
    O.S.DEL PERSONAL DE PRENSA DE LA PROVINCIA DE CHACO
600309 No encontrado
    ASOCIACION DE OBRAS SOCIALES DE BELLA VISTA

000208 Encrontrado. Tipos: ['1', '6']
    Names:
    O.S.DEL PERSONAL DE LA INDUSTRIA GRAFICA DE LA PROVINCIA DE CORDOBA
    OBRA SOCIAL DEL  PERSONAL DE LA INDUSTRIA GRAFICA DE LA PROVINCIA DE CORDOBA
000307 Encrontrado. Tipos: ['1', '6']
    Names:
    O.S.PORTUARIOS ARGENTINOS DE MAR DEL PLATA
    OBRA SOCIAL PORTUARIOS ARGENTINOS DE MAR DEL PLATA
000406 Encrontrado. Tipos: ['1', '6']
    Names:
    O.S.DEL PERSONAL DE ORGANISMOS DE CONTROL EXTERNO
    OBRA SOCIAL DEL PERSONAL DEL ORGANISMO DE CONTROL EXTERNO
000505 Encrontrado. Tipos: ['1', '5', '6']
    Names:
    O.S.DE CAPITANES,PILOTOS Y PATRONES DE PESCA
    OBRA SOCIAL DE CAPITANES, PILOTOS Y PATRONES DE PESCA
000604 Encrontrado. Tipos: ['1', '4', '6']
    Names:
    O.S.DE AGENTES DE LOTERIAS Y AFINES DE LA REPUBLICA ARGENTINA
    OBRA SOCIAL DE AGENTES DE LOTERIAS Y AFINES DE LA REPUBLICA  ARGENTINA
000703 Encrontrado. Tipos: ['1', '4', '5', '16']
    Names:
    MUTUAL DEL PERSONAL DE AGUA Y ENERGIA DE MENDOZA
    MUTUAL DEL PERSONAL DEL AGUA Y LA ENERGIA  DE MENDOZA
000901 Encrontrado. Tipos: ['1', '4', '5', '6']
    Names:
    O.S.DE LA ACTIVIDAD DE SEGUROS,REASEGUROS,CAPITALIZACION Y AHORRO Y PRESTAMO PARA LA VIVIENDA
    OBRA SOCIAL DE LA ACTIVIDAD DE SEGUROS, REASEGUROS, CAPITALIZACION Y AHORRO Y PRESTAMO PARA LA VIVIENDA
001102 Encrontrado. Tipos: ['1', '6']
    Names:
    O.S.PARA LA ACTIVIDAD DOCENTE
    OBRA SOCIAL PARA LA ACTIVIDAD DOCENTE
001201 Encrontrado. Tipos: ['1', '6']
    Names:
    O.S.PARA EL PERSONAL DEL MINISTERIO DE ECONOMIA Y OBRAS PUBLICAS
    OBRA SOCIAL PARA EL PERSONAL DEL MINISTERIO DE ECONOMIA Y DE OBRAS Y SERVICIOS PUBLICOS
001300 Encrontrado. Tipos: ['1', '5', '6']
    Names:
    O.S.FERROVIARIA
    OBRA SOCIAL FERROVIARIA
001508 Encrontrado. Tipos: ['1', '6']
    Names:
    OS. ASOCIACION CIVIL PRO SINDICATO AMAS DE CASA DE LA REPUBLICA ARGENTINA
    OBRA SOCIAL DE LA ASOCIACION CIVIL PROSINDICATO DE AMAS DE CASA DE LA REPUBLICA ARGENTINA
001607 Encrontrado. Tipos: ['1', '6']
    Names:
    O.S.DEL SINDICATO UNIDO DE TRABAJADORES DE LA INDUSTRIA DE AGUAS GASEOSAS DE LA PROVINCIA DE SANTA FE
    OBRA SOCIAL DEL SINDICATO UNIDO DE TRABAJADORES DE LA INDUSTRIA DE AGUAS GASEOSAS DE LA PROVINCIA DE SANTA FE
001706 Encrontrado. Tipos: ['1', '5', '6']
    Names:
    O.S.DEL PERSONAL JERARQUICO DE LA REPUBLICA ARGENTINA PARA EL PERSONAL JERARQUICO DE LA INDUSTRIA GRAFICA
        Y EL PERSONAL JERARQUICO DE AGUA Y ENERGIA
    OBRA SOCIAL DEL PERSONAL JERARQUICO DE LA REPUBLICA ARGENTINA PARA EL PERSONAL JERARQUICO DE LA INDUSTRIA GRAFICA
        Y EL PERSONAL JERARQUICO DEL AGUA Y LA ENERGIA
001805 Encrontrado. Tipos: ['1', '4', '6']
    Names:
    Obra Social de Legisladores de la Republica Argentina
    OBRA SOCIAL DE LOS  LEGISLADORES DE LA REPUBLICA ARGENTINA
001904 Encrontrado. Tipos: ['1', '4', '6']
    Names:
    O.S.DE LA FEDERACION DE CAMARAS Y CENTROS COMERCIALES ZONALES DE LA REPUBLICA ARGENTINA
    OBRA SOCIAL DE FEDECAMARAS
002105 Encrontrado. Tipos: ['1', '6']
    Names:
    O.S. PROFESIONALES DEL TURF DE LA REPUBLICA ARGENTINA
    OBRA SOCIAL PROFESIONALES DEL TURF DE LA REPUBLICA ARGENTINA
002204 Encrontrado. Tipos: ['1', '4', '5', '6']
    Names:
    OS. EMPLEADOS Y PERSONAL JERARQUICO DEL NEUMATICO ARGENTINO DE NEUMATICOS GOOD YEAR S.R.L.
    OBRA SOCIAL DE EMPLEADOS Y PERSONAL JERARQUICO  DE LA ACTIVIDAD DEL  NEUMATICO ARGENTINO DE NEUMATICOS GOOD YEAR SRL
002303 Encrontrado. Tipos: ['1', '6']
    Names:
    O.S. PARA EL PERSONAL DE EMPRESAS DE LIMPIEZA, SERVICIOS Y MAESTRANZA DE MENDOZA
    OBRA SOCIAL PARA EL  PERSONAL DE EMPRESAS DE  LIMPIEZA, SERVICIOS Y MAESTRANZA DE MENDOZA
002402 Encrontrado. Tipos: ['1', '6']
    Names:
    O.S. DEL PERSONAL JERARQUICO DEL TRANSPORTE AUTOMOTOR DE PASAJEROS DE CORDOBA Y AFINES
    OBRA SOCIAL DEL PERSONAL JERARQUICO DEL TRANSPORTE AUTOMOTOR DE PASAJEROS DE CORDOBA Y AFINES
002501 Encrontrado. Tipos: ['1', '6']
    Names:
    O.S.DE MINISTROS, SECRETARIOS Y SUBSECRETARIOS
    OBRA SOCIAL DE MINISTROS, SECRETARIOS Y SUBSECRETARIOS
002600 Encrontrado. Tipos: ['1', '6']
    Names:
    O.S. DE LA TRABAJADORES DE LA CARNE Y AFINES DE LA R.A.
    OBRA SOCIAL DE LOS TRABAJADORES DE LA CARNE Y AFINES DE LA REPUBLICA ARGENTINA
002709 Encrontrado. Tipos: ['1', '5', '6']
    Names:
    OS DE LOS TRABAJADORES ASOCIADOS A LA ASOCIACION MUTUAL MERCANTIL ARGENTINA (OSTAMMA)
    OBRA SOCIAL DE LOS TRABAJADORES ASOCIADOS A LA ASOCIACION MUTUAL MERCANTIL ARGENTINA
002808 Encrontrado. Tipos: ['1', '4', '6']
    Names:
    OS DE LA CAMARA DE EMPRESARIOS DE AGENCIAS DE REMISES DE LA PROVINCIA DE BUENOS AIRES (O.S.C.E.A.R.B.A)
    OBRA SOCIAL DE LA CAMARA DE EMPRESARIOS DE AGENCIAS DE REMISES DE ARGENTINA
002907 Encrontrado. Tipos: ['1', '6']
    Names:
    O. S. ASOCIACION MUTUAL METALURGICA VILLA CONSTITUCION (O.S.A.M.M.V.C)
    OBRA SOCIAL ASOCIACION MUTUAL METALURGICA VILLA CONSTITUCION
003009 Encrontrado. Tipos: ['1', '6']
    Names:
     O.S.PERSONAL ASOCIADO A ASOC.MUTUAL SANCOR (O.S.PERS.A.A.M.S)
    OBRA SOCIAL DEL PERSONAL ASOCIADO A ASOCIACION MUTUAL SANCOR
003108 Encrontrado. Tipos: ['1', '5', '6']
    Names:
    OS DE LOS INMIGRANTES ESPANOLES Y SUS DESCENDIENTES RESIDENTES DE LA RA
    OBRA SOCIAL DE LOS INMIGRANTES ESPAÑOLES Y SUS DESCENDIENTES RESIDENTES EN LA REPUBLICA ARGENTINA
003207 Encrontrado. Tipos: ['1', '5', '6']
    Names:
    OS DE TRABAJADORES SOCIOS DE LA ASOCIACION MUTUAL DEL PERSONAL JERARQUICO DE BANCOS OFICIALES - JERARQUICO SALUD
    OBRA SOCIAL DE TRABAJADORES SOCIOS DE LA ASOCIACION MUTUAL DEL PERSONAL JERARQUICO DE BANCOS OFICIALES
        NACIONALES-JERARQUICOS SALUD-
003306 Encrontrado. Tipos: ['1', '6']
    Names:
    OS TRABAJADORES VENDEDORES DE DIARIOS, REVISTAS Y AFINES (OSTVENDRA)
    OBRA SOCIAL DE TRABAJADORES VENDEDORES DE DIARIOS REVISTAS Y AFINES
003405 Encrontrado. Tipos: ['1', '2', '3', '6']
    Names:
    OS DE LA ASOCIACION MUTUAL DE LOS OBREROS CATOLICOS PADRE FEDERICO GROTE
    OBRA SOCIAL ASOCIACION  MUTUAL DE LOS OBREROS CATOLICOS PADRE FEDERICO GROTE
003504 Encrontrado. Tipos: ['1', '6']
    Names:
    OS CONDUCTORES TITULARES DE TAXIS DE LA CDAD AUT. BS.AS.
    OBRA SOCIAL DE CONDUCTORES TITULARES DE TAXIS DE LA CIUDAD AUTONOMA DE BUENOS AIRES
003603 Encrontrado. Tipos: ['1', '2', '3', '6']
    Names:
    OBRA SOCIAL PROGRAMAS MEDICOS SOCIEDAD ARGENTINA DE CONSULTORIA MUTUAL
    OBRA SOCIAL PROGRAMAS MEDICOS SOCIEDAD ARGENTINA DE CONSULTORIA MUTUAL
003702 Encrontrado. Tipos: ['1', '6']
    Names:
    OBRA SOCIAL YACIMIENTOS CARBONIFEROS
    OBRA SOCIAL  YACIMIENTOS CARBONIFEROS
003801 Encrontrado. Tipos: ['1', '6']
    Names:
    OBRA SOCIAL DE LA PREVENCIÓN Y LA SALUD
    OBRA SOCIAL  DE LA PREVENCION Y LA SALUD
003900 Encrontrado. Tipos: ['1', '6']
    Names:
    OBRA SOCIAL TÉCNICOS  DE VUELO LINEAS AEREAS
    OBRA SOCIAL DE TECNICOS DE VUELO DE LINEAS AEREAS
100106 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.PARA EL PERSONAL DE LA INDUSTRIA ACEITERA Y AFINES
    OBRA SOCIAL PARA EL PERSONAL DE LA INDUSTRIA ACEITERA, DESMOTADORA Y AFINES
100205 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.DE  ACTORES
    OBRA SOCIAL DE ACTORES
100403 Encrontrado. Tipos: ['1', '4', '5', '7']
    Names:
    O.S.DEL PERSONAL SUPERIOR Y PROFESIONAL DE EMPRESAS AEROCOMERCIALES
    OBRA SOCIAL DEL PERSONAL SUPERIOR Y PROFESIONAL DE EMPRESAS AEROCOMERCIALES
100502 Encrontrado. Tipos: ['1', '4', '5', '7']
    Names:
    O.S.DEL PERSONAL AERONAUTICO
    OBRA SOCIAL DEL PERSONAL AERONAUTICO
100601 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S.DEL PERSONAL AERONAVEGACION DE ENTES PRIVADOS
    OBRA SOCIAL DEL PERSONAL DE AERONAVEGACION DE ENTES PRIVADOS
100700 Encrontrado. Tipos: ['1', '4', '5', '7']
    Names:
    O.S.DEL PERSONAL TECNICO AERONAUTICO
    OBRA SOCIAL DEL PERSONAL TECNICO AERONAUTICO
100809 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.DE  AERONAVEGANTES
    OBRA SOCIAL DE AERONAVEGANTES
100908 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S.DE EMPLEADOS DE AGENCIAS DE INFORMES
    OBRA SOCIAL  EMPLEADOS DE AGENCIAS DE INFORMES
101000 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE AGUAS GASEOSAS Y AFINES
    OBRA SOCIAL DEL PERSONAL DE AGUAS GASEOSAS Y AFINES
101208 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE LA INDUSTRIA DE LA ALIMENTACION
    OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DE LA ALIMENTACION
101604 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S.DEL PERSONAL DEL AUTOMOVIL CLUB ARGENTINO
    OBRA SOCIAL DEL PERSONAL DEL AUTOMOVIL  CLUB ARGENTINO
101802 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE AZUCAR DEL INGENIO LA ESPERANZA
    OBRA SOCIAL DEL PERSONAL DEL AZUCAR DEL INGENIO LA ESPERANZA
101901 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE AZUCAR DEL INGENIO LEDESMA
    OBRA SOCIAL DEL PERSONAL DEL AZUCAR DEL INGENIO LEDESMA
102300 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.DEL PERSONAL DE AZUCAR DEL INGENIO SAN MARTIN
    OBRA SOCIAL DEL PERSONAL DEL AZUCAR DEL INGENIO SAN MARTIN
102706 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S.DEL PERSONAL DE LA INDUSTRIA AZUCARERA
    OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA AZUCARERA
102904 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S.DEL PERSONAL DE BARRACAS DE LANAS,CUEROS Y ANEXOS
    OBRA SOCIAL DEL PERSONAL DE BARRACAS DE LANAS, CUEROS Y ANEXOS
103006 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE LA INDUSTRIA BOTONERA
    OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA BOTONERA
103105 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S.DEL PERSONAL DE LA INDUSTRIA DEL CALZADO
    OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL CALZADO
103204 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE CONDUCTORES CAMIONEROS Y PERSONAL DEL TRANSPORTE AUTOMOTOR DE CARGAS
    OBRA SOCIAL DE CONDUCTORES CAMIONEROS Y PERSONAL DEL TRANSPORTE AUTOMOTOR DE CARGAS
103402 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE CARGA Y DESCARGA
    OBRA SOCIAL DEL PERSONAL DE CARGA Y DESCARGA
103600 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S.DEL PERSONAL AUXILIAR DE CASAS PARTICULARES
    OBRA SOCIAL DEL PERSONAL AUXILIAR DE CASAS PARTICULARES
103709 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE LA INDUSTRIA DEL CAUCHO
    OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL CAUCHO
103808 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DEL CAUCHO
    OBRA SOCIAL DEL PERSONAL DEL CAUCHO
103907 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.DEL PERSONAL DE LA INDUSTRIA DEL CAUCHO DE SANTA FE
    OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL CAUCHO DE SANTA FE
104009 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S.DEL PERSONAL DE CEMENTERIOS DE LA REPUBLICA ARGENTINA
    OBRA SOCIAL DEL PERSONAL DE CEMENTERIOS DE LA REPUBLICA ARGENTINA.
104108 Encrontrado. Tipos: ['1', '4', '5', '7']
    Names:
    O.S.DE CERAMISTAS
    OBRA SOCIAL DE CERAMISTAS
104207 Encrontrado. Tipos: ['1', '4', '5', '7']
    Names:
    O.S.DEL PERSONAL DE LA CERAMICA,SANITARIOS,PORCELANAS DE MESA Y AFINES
    OBRA SOCIAL DEL PERSONAL DE LA CERAMICA, SANITARIOS, PORCELANA DE MESA Y AFINES
104306 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE LA ACTIVIDAD CERVECERA Y AFINES
    OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD CERVECERA Y AFINES
104405 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL CINEMATOGRAFICO DE MAR DEL PLATA
    OBRA SOCIAL DEL PERSONAL CINEMATOGRAFICO DE MAR DEL PLATA
104504 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE LA INDUSTRIA CINEMATOGRAFICA
    OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA CINEMATOGRAFICA
104603 Encrontrado. Tipos: ['1', '2', '3', '7']
    Names:
    O.S.DE OPERADORES CINEMATOGRAFICOS
    OBRA SOCIAL DE OPERADORES CINEMATOGRAFICOS
104801 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE COLOCADORES DE AZULEJOS,MOSAICOS,GRANITEROS,LUSTRADORES Y PORCELANEROS
    OBRA SOCIAL DE COLOCADORES DE AZULEJOS, MOSAICOS, GRANITEROS, LUSTRADORES Y PORCELANEROS
105002 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.DE CONDUCTORES NAVALES (CONDUCTORES FUSIONADOS)
    OBRA SOCIAL DE CONDUCTORES NAVALES
105309 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL ADMINISTRATIVO Y TECNICO DE LA CONSTRUCCION Y AFINES
    OBRA SOCIAL DEL PERSONAL ADMINISTRATIVO Y TECNICO DE LA CONSTRUCCION Y AFINES
105408 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE LA CONSTRUCCION
    OBRA SOCIAL DEL PERSONAL DE LA CONSTRUCCION
105507 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.DE LOS CORTADORES DE LA INDUMENTARIA
    OBRA SOCIAL DE LOS CORTADORES DE LA INDUMENTARIA
105606 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE LA INDUSTRIA DEL CUERO Y AFINES
    OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL CUERO Y AFINES
105705 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.DEL PERSONAL DE LA INDUSTRIA DEL CHACINADO Y AFINES
    OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL CHACINADO Y AFINES
105804 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.DE CHOFERES DE CAMIONES
    OBRA SOCIAL DE CHOFERES DE CAMIONES
106005 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE  ENTIDADES DEPORTIVAS Y CIVILES
    OBRA SOCIAL DEL PERSONAL DE ENTIDADES DEPORTIVAS Y CIVILES
106104 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.EMPLEADOS DE DESPACHANTES DE ADUANA
    OBRA SOCIAL DE EMPLEADOS DE DESPACHANTES DE ADUANA
106203 Encrontrado. Tipos: ['1', '2', '3', '4', '7']
    Names:
    O.S.DEL PERSONAL DE DISTRIBUIDORAS CINEMATOGRAFICAS
    OBRA SOCIAL DEL PERSONAL DE DISTRIBUIDORAS CINEMATOGRAFICAS DE LA R.A.
106302 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE DOCENTES PARTICULARES
    OBRA SOCIAL DE DOCENTES PARTICULARES
106401 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE EDIFCIOS DE RENTA Y HORIZONTAL DE LA REPUBLICA ARGENTINA
    OBRA SOCIAL DEL PERSONAL DE EDIFICIOS DE RENTA Y HORIZONTAL DE LA REPUBLICA ARGENTINA
106500 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE EDIFICIOS DE RENTAS Y HORIZONTAL DE CAPITAL FEDERAL Y GRAN BUENOS ARIES
    OBRA SOCIAL DEL PERSONAL DE EDIFICIOS DE RENTA Y HORIZONTAL DE LA CIUDAD AUTONOMA DE BUENOS AIRES  Y GRAN BUENOS AIRES
106609 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.ELECTRICISTAS NAVALES
    OBRA SOCIAL ELECTRICISTAS NAVALES
106708 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE OBREROS EMPACADORES DE FRUTA DE RIO NEGRO Y NEUQUEN
    OBRA SOCIAL DE OBREROS EMPACADORES DE FRUTA  DE RIO NEGRO Y NEUQUEN
106807 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE LA ENSEÑANZA PRIVADA
    OBRA SOCIAL DEL PERSONAL DE LA ENSEÑANZA PRIVADA
106906 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.DEL PERSONAL DE ESCRIBANIAS DE LA PROVINCIA DE BUENOS AIRES
    OBRA SOCIAL DEL PERSONAL DE ESCRIBANIAS DE LA PROVINCIA DE BUENOS AIRES
107008 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE ESCRIBANOS
    OBRA SOCIAL DEL PERSONAL DE ESCRIBANOS
107107 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DEL ESPECTACULO PUBLICO
    OBRA SOCIAL DEL PERSONAL DEL ESPECTACULO PUBLICO
107206 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE ESTACIONES DE SERVICIO Y GNC,GARAGES,PLAYAS DE ESTACIONAMIENTO Y LAVADEROS AUTOMATICOS
    OBRA SOCIAL DEL PERSONAL DE ESTACIONES DE SERVICIO Y G.N.C, GARAGES, PLAYAS DE ESTACIONAMIENTO Y LAVADEROS AUTOMATICOS
107404 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE FARMACIA
    OBRA SOCIAL DEL PERSONAL DE FARMACIA
107800 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S.DEL PERSONAL DE LA INDUSTRIA DEL FIBROCEMENTO
    OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL FIBROCEMENTO
107909 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE LA INDUSTRIA FIDEERA
    OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA FIDEERA
108001 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S.DEL PERSONAL DE LA INDUSTRIA FORESTAL DE SANTIAGO DEL ESTERO
    OBRA SOCIAL  PARA EL PERSONAL DE LA INDUSTRIA FORESTAL DE SANTIAGO DEL ESTERO
108100 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S.DEL PERSONAL DE LA INDUSTRIA DEL FOSFORO
    OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL FOSFORO, ENCENDIDO Y AFINES
108209 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S.DE FOTOGRAFOS
    OBRA SOCIAL DE FOTOGRAFOS
108407 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE LA ACTIVIDAD  FRUCTICOLA
    OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD FRUTICOLA
108506 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE MANIPULEO,EMPAQUE Y EXPEDICION DE FRUTA FRESCA Y HORTALIZAS DE CUYO
    OBRA SOCIAL DEL PERSONAL DE MANIPULEO, EMPAQUE Y EXPEDICION DE FRUTA FRESCA Y HORTALIZAS DE CUYO
108605 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE FUTBOLISTAS
    OBRA SOCIAL DE FUTBOLISTAS
108704 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE TECNICOS DE FUTBOL
    OBRA SOCIAL DE TECNICOS DE FUTBOL
108803 Encrontrado. Tipos: ['1', '4', '5', '7']
    Names:
    OS DEL PERSONAL DE LA UNION DE TRABAJADORES DEL TURISMO, HOTELEROS Y GASTRONOMICOS DE LA RA (OSUTHGRA)
    OBRA SOCIAL  DE LA UNION  DE TRABAJADORES  DEL TURISMO, HOTELEROS Y GASTRONOMICOS DE LA REPUBLICA  ARGENTINA
109004 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL GRAFICO
    OBRA SOCIAL DEL PERSONAL GRAFICO
109202 Encrontrado. Tipos: ['1', '4', '5', '7']
    Names:
    O.S.DE GUINCHEROS Y MAQUINISTAS DE GRUAS MOVILES
    OBRA SOCIAL DE GUINCHEROS Y MAQUINISTAS DE GRUAS MOVILES
109301 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE CONSIGNATARIOS DEL MERCADO NACIONAL DE HACIENDA DE LINIERS
    OBRA SOCIAL DEL PERSONAL DE CONSIGNATARIOS DEL MERCADO NACIONAL DE HACIENDA DE LINIERS
109400 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.DEL PERSONAL DE LA INDUSTRIA DEL HIELO Y MERCADOS PARTICULARES
    OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL HIELO Y MERCADOS PARTICULARES
109509 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE LOS HIPODROMOS DE BUENOS AIRES Y SAN ISIDRO
    OBRA SOCIAL DEL PERSONAL DE LOS HIPODROMOS DE BUENOS AIRES Y SAN ISIDRO
109608 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.Y SINDICATO DEL PERSONAL MENSUALIZADO DEL JOCKEY CLUB DE BUENOS AIRES Y LOS HIPODROMOS DE PALERMO Y SAN ISIDRO
    OBRA SOCIAL DEL PERSONAL MENSUALIZADO DEL JOCKEY CLUB DE BUENOS AIRES Y LOS HIPODROMOS DE PALERMO Y SAN ISIDRO
109707 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE IMPRENTA, DIARIOS Y AFINES
    OBRA SOCIAL DEL PERSONAL DE IMPRENTAS, DIARIOS Y AFINES
110008 Encrontrado. Tipos: ['1', '4', '5', '7']
    Names:
    O.S.DEL PERSONAL DE JABONEROS
    OBRA SOCIAL DEL PERSONAL DE JABONEROS
110107 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S.DE JARDINEROS,PARQUISTAS,VIVERISTAS Y FLORICULTORES
    OBRA SOCIAL DE JARDINEROS, PARQUISTAS, VIVERISTAS Y FLORICULTORES DE LA REPUBLICA ARGENTINA
110206 Encrontrado. Tipos: ['1', '4', '5', '7']
    Names:
    O.S.DEL PERSONAL DEL JOCKEY CLUB DE ROSARIO
    OBRA SOCIAL DEL PERSONAL DEL JOCKEY CLUB DE ROSARIO
110305 Encrontrado. Tipos: ['1', '2', '4', '7']
    Names:
    O.S.DEL PERSONAL LADRILLERO
    OBRA SOCIAL DEL PERSONAL LADRILLERO
110404 Encrontrado. Tipos: ['1', '2', '7']
    Names:
    O.S.DEL PERSONAL DE LA INDUSTRIA LADRILLERA A MAQUINA
    OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA LADRILLERA A MAQUINA
110503 Encrontrado. Tipos: ['1', '4', '5', '7']
    Names:
    O.S.DEL PERSONAL DE LA INDUSTRIA LECHERA
    OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA LECHERA
110602 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE LOCUTORES
    OBRA SOCIAL DE LOCUTORES
110701 Encrontrado. Tipos: ['1', '4', '5', '7']
    Names:
    O.S.DE LA FEDERACION ARGENTINA DE TRABAJADORES DE LUZ Y FUERZA
    OBRA SOCIAL DE LA FEDERACION ARGENTINA DE TRABAJADORES DE LUZ Y FUERZA
110800 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.DE LOS TRABAJADORES DE LAS EMPRESAS DE ELECTRICIDAD
    OBRA SOCIAL DE LOS TRABAJADORES DE LAS EMPRESAS DE ELECTRICIDAD
110909 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.DEL PERSONAL DE LUZ Y FUERZA DE CORDOBA
    OBRA SOCIAL DEL PERSONAL DE LUZ Y FUERZA DE CORDOBA
111001 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE LA INDUSTRIA MADERERA
    OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA MADERERA
111209 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE MAESTRANZA
    OBRA SOCIAL DEL PERSONAL DE MAESTRANZA
111308 Encrontrado. Tipos: ['1', '2', '3', '7']
    Names:
    O.S.DE MAQUINISTAS DE TEATRO Y TELEVISION
    OBRA SOCIAL DE MAQUINISTAS DE TEATRO Y TELEVISION
111407 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.DE CAPITANES DE ULTRAMAR Y OFICIALES DE LA MARINA MERCANTE
    OBRA SOCIAL DE CAPITANES DE ULTRAMAR Y OFICIALES DE LA MARINA MERCANTE
111506 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE CAPITANES BAQUEANOS FLUVIALES DE LA MARINA MERCANTE
    OBRA SOCIAL ASOCIACION PROFESIONAL DE CAPITANES Y BAQUEANOS FLUVIALES Y PERSONAL CON  CONOCIMIENTO DE ZONA
        DE LA MARINA MERCANTE
111605 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE EMPLEADOS DE LA MARINA MERCANTE
    OBRA SOCIAL DE EMPLEADOS DE LA MARINA MERCANTE
111704 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE ENCARGADOS APUNTADORES MARITIMOS
    OBRA SOCIAL DE ENCARGADOS APUNTADORES MARITIMOS
111803 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL MARITIMO
    OBRA SOCIAL DEL PERSONAL MARITIMO
111902 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.DEL SINDICATO DE MECANICOS Y AFINES DEL TRANSPORTE AUTOMOTOR
    OBRA SOCIAL DEL SINDICATO DE MECANICOS Y AFINES DEL TRANSPORTE AUTOMOTOR
112004 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.DEL PERSONAL SUPERIOR DE MERCEDES BENZ ARGENTINA
    OBRA SOCIAL DEL PERSONAL SUPERIOR MERCEDES BENZ ARGENTINA
112103 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S. DE LA UNION OBRERA METALURGICO DE LA REPUBLICA ARGENTINA
    OBRA SOCIAL DE LA UNION OBRERA METALURGICA DE LA REPUBLICA ARGENTINA
112202 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE LOS SUPERVISORES DE LA INDUSTRIA METALMECANICA DE LA REPUBLICA ARGENTINA
    OBRA SOCIAL DE LOS  SUPERVISORES DE LA INDUSTRIA METALMECANICA DE LA REPUBLICA ARGENTINA
112301 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE MICROS Y OMNIBUS DE MENDOZA
    OBRA SOCIAL DEL PERSONAL DE  MICROS Y OMNIBUS DE MENDOZA
112400 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE LA ACTIVIDAD MINERA
    OBRA SOCIAL DE LA ACTIVIDAD MINERA
112509 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.MODELOS ARGENTINOS
    OBRA SOCIAL MODELOS ARGENTINOS
112608 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE LA INDUSTRIA MOLINERA
    OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA MOLINERA
112707 Encrontrado. Tipos: ['1', '4', '5', '7']
    Names:
    O.S.DEL PERSONAL MOSAISTA
    OBRA SOCIAL DEL PERSONAL MOSAISTA
112806 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S.DE MUSICOS
    OBRA SOCIAL DE MUSICOS
113205 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE JEFES Y OFICIALES NAVALES DE RADIOCOMUNICACIONES
    OBRA SOCIAL DE JEFES Y OFICIALES NAVALES DE RADIOCOMUNICACIONES
113304 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE JEFES Y OFICIALES MAQUINISTAS NAVALES
    OBRA SOCIAL DE JEFES Y OFICIALES MAQUINISTAS NAVALES
113403 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL NAVAL
    OBRA SOCIAL DEL PERSONAL NAVAL
113601 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE LA INDUSTRIA DEL NEUMATICO
    OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL NEUMATICO
113700 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S.DEL PERSONAL DE LA INDUSTRIA NAVAL
    OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA NAVAL
113809 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE COMISARIOS NAVALES
    OBRA SOCIAL DE COMISARIOS NAVALES
113908 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S.DEL PERSONAL DE PANADERIAS
    OBRA SOCIAL DEL PERSONAL DE PANADERIAS
114000 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE PANADEROS,PASTELEROS Y FACTUREROS DE ENTRE RIOS
    OBRA SOCIAL DE PANADEROS, PASTELEROS Y FACTUREROS DE ENTRE RIOS
114109 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DEL PAPEL,CARTON Y QUIMICOS
    OBRA SOCIAL DEL PERSONAL DEL PAPEL, CARTON Y QUIMICOS
114208 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.DE LA INDUSTRIA DE PASTAS ALIMENTICIAS
    OBRA SOCIAL DE LA INDUSTRIA DE PASTAS ALIMENTICIAS
114307 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE PASTELEROS,CONFITEROS,PIZZEROS Y ALFAJOREROS DE LA REPUBLICA ARGENTINA
    OBRA SOCIAL TRABAJADORES  PASTELEROS, CONFITEROS, PIZZEROS , HELADEROS Y ALFAJOREROS DE LA REPUBLICA ARGENTINA
114505 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S.DE PATRONES DE CABOTAJE DE RIOS Y PUERTOS
    OBRA SOCIAL DE PATRONES DE CABOTAJE DE RIOS Y PUERTOS
114703 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE PELUQUERIAS,ESTETICA Y AFINES
    OBRA SOCIAL DEL PERSONAL DE PELUQUERIAS, ESTETICAS Y AFINES
114901 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE OFICIALES PELUQUEROS Y PEINADORES DE ROSARIO
    OBRA SOCIAL DE OFICIALES PELUQUEROS Y PEINADORES  DE LA 2DA CIRCUNSCRIPCION JUDICIAL DE LA PROVINCIA DE SANTA FE
115003 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE LA ACTIVIDAD PERFUMISTA
    OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD PERFUMISTA
115102 Encrontrado. Tipos: ['1', '2', '3', '7']
    Names:
    O.S.DE TRABADORES DE PRENSA DE BUENOS AIRES
    OBRA SOCIAL DE TRABAJADORES DE PRENSA DE BUENOS AIRES
115201 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE LA INDUSTRIA DEL PESCADO DE MAR DEL PLATA
    OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL PESCADO DE MAR DEL PLATA
115300 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S.PETROLEROS
    OBRA SOCIAL DE PETROLEROS
115409 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PETROLEO Y GAS PRIVADO
    OBRA SOCIAL DEL PETROLEO Y GAS PRIVADOS
115508 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE PETROLEROS DE CORDOBA
    OBRA SOCIAL DE PETROLEROS DE CORDOBA
115607 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE LA INDUSTRIA PETROQUIMICA
    OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA PETROQUIMICA
115706 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.DE PILOTOS DE LINEAS AEREAS COMERCIALES Y REGULARES
    OBRA SOCIAL PARA PILOTOS DE LINEAS AEREAS COMERCIALES Y REGULARES
115805 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE FABRICAS DE PINTURA
    OBRA SOCIAL DEL PERSONAL DE FABRICAS DE PINTURA
116006 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE LA INDUSTRIA DEL PLASTICO
    OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL PLASTICO
116105 Encrontrado. Tipos: ['1', '2', '3', '5', '7']
    Names:
    O.S.DE CAPATACES Y ESTIBADORES PORTUARIOS
    OBRA SOCIAL DE CAPATACES  ESTIBADORES PORTUARIOS
116204 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE PORTUARIOS ARGENTINOS
    OBRA SOCIAL DE PORTUARIOS ARGENTINOS
116709 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S.PORTUARIOS DE PUERTO SAN MARTIN Y BELLA VISTA
    OBRA SOCIAL PORTUARIOS  PUERTO SAN MARTIN Y BELLA VISTA
117207 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE PRENSA DE LA REPUBLICA ARGENTINA
    OBRA SOCIAL DEL PERSONAL DE PRENSA DE LA REPUBLICA ARGENTINA
117405 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE PRENSA DE BAHIA BLANCA
    OBRA SOCIAL DEL PERSONAL DE PRENSA DE BAHIA BLANCA
117603 No encontrado en nuestra base de datos
    117603 - O.S.DEL PERSONAL DE PRENSA DE LA PROVINCIA DE CHACO
117702 Encrontrado. Tipos: ['1', '2', '3', '4', '7']
    Names:
    O.S.DEL PERSONAL DE PRENSA DE MAR DEL PLATA
    OBRA SOCIAL DEL PERSONAL DE PRENSA DE MAR DEL PLATA
117801 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S.DEL PERSONAL DE PRENSA DE MENDOZA
    OBRA SOCIAL DEL PERSONAL DE PRENSA DE MENDOZA
118002 Encrontrado. Tipos: ['1', '2', '3', '4', '5', '7']
    Names:
    O.S.DE EMPLEADOS DE PRENSA DE CORDOBA
    OBRA SOCIAL DE EMPLEADOS DE PRENSA DE CORDOBA
118200 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.DE AGENTES DE PROPAGANDA MEDICA DE LA REPUBLICA ARGENTINA
    OBRA SOCIAL DE AGENTES DE PROPAGANDA MEDICA DE LA REPUBLICA ARGENTINA
118309 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S.DE AGENTES DE PROPAGANDA MEDICA DE CORDOBA
    OBRA SOCIAL DE AGENTES DE PROPAGANDA MEDICA DE CORDOBA
118408 Encrontrado. Tipos: ['1', '4', '5', '7']
    Names:
    O.S.DE AGENTES DE PROPAGANDA MEDICA DE ENTRE RIOS
    OBRA SOCIAL DE AGENTES DE PROPAGANDA MEDICA DE ENTRE RIOS
118606 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE LA PUBLICIDAD
    OBRA SOCIAL DEL PERSONAL DE LA PUBLICIDAD
118705 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE INDUSTRIAS QUIMICAS Y PETROQUIMICAS
    OBRA SOCIAL DEL PERSONAL DE INDUSTRIAS QUIMICAS Y PETROQUIMICAS
118804 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE RECIBIDORES DE GRANOS Y ANEXOS
    OBRA SOCIAL DE RECIBIDORES DE GRANOS Y ANEXOS
118903 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE RECOLECCION Y BARRIDO DE ROSARIO
    OBRA SOCIAL DEL PERSONAL DE RECOLECCION Y BARRIDO DE ROSARIO
119005 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE REFINERIAS DE MAIZ
    OBRA SOCIAL DEL PERSONAL DE REFINERIAS DE MAIZ
119203 Encrontrado. Tipos: ['5', '7']
    Names:
    O.S.DE RELOJEROS Y JOYEROS
    OBRA SOCIAL DE RELOJEROS Y JOYEROS
119302 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.DEL PERSONAL RURAL Y ESTIBADORES DE LA REPUBLICA  ARGENTINA
    OBRA SOCIAL DEL PERSONAL RURAL Y ESTIBADORES DE LA REPUBLICA ARGENTINA
119500 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.DEL PERSONAL DE LA SANIDAD ARGENTINA
    OBRA SOCIAL DEL PERSONAL DE LA SANIDAD ARGENTINA
119609 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE INSTALACIONES SANITARIAS
    OBRA SOCIAL DEL PERSONAL DE INSTALACIONES SANITARIAS
119708 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE SEGURIDAD COMERCIAL,INDUSTRIAL E INVESTIGACIONES PRIVADAS
    OBRA SOCIAL DEL PERSONAL DE SEGURIDAD COMERCIAL, INDUSTRIAL E INVESTIGACIONES PRIVADAS
119906 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.DE SERENOS DE BUQUES
    OBRA SOCIAL DE SERENOS DE BUQUES
120306 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE SUPERVISION DE LA EMPRESA SUBTERRANEOS DE BUENOS AIRES
    OBRA SOCIAL DEL PERSONAL DE SUPERVISION DE LA EMPRESA SUBTERRANEOS DE BUENOS AIRES
120405 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S.DEL PERSONAL DE DIRECCION DE LA EMPRESA SUBTERRANEOS BUENOS AIRES
    OBRA SOCIAL DEL PERSONAL DE DIRECCION DE LA EMPRESA SUBTERRANEOS DE BUENOS AIRES
120504 Encrontrado. Tipos: ['1', '4', '5', '7']
    Names:
    O.S.DEL PERSONAL DE LA INDUSTRIA DEL TABACO
    OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA  DEL TABACO
120603 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.DE EMPLEADOS DEL TABACO
    OBRA SOCIAL DE EMPLEADOS DEL TABACO DE LA REPUBLICA ARGENTINA
120702 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S. DEL PERSONAL DE LAS TELECOMUNICACIONES DE LA REPUBLICA ARGENTINA
    OBRA SOCIAL DEL PERSONAL DE LAS TELECOMUNICACIONES DE LA REPUBLICA ARGENTINA
120801 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.DE TRABAJADORES DE LAS COMUNICACIONES (OSTRAC)
    OBRA SOCIAL DE TRABAJADORES DE LAS COMUNICACIONES
120900 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE TELEVISION
    OBRA SOCIAL DEL PERSONAL DE TELEVISION
121002 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE LA INDUSTRIA TEXTIL
    OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA TEXTIL
121101 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE EMPLEADOS TEXTILES Y AFINES
    OBRA SOCIAL DE EMPLEADOS TEXTILES Y AFINES
121309 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.DEL PERSONAL DE LA INDUSTRIA DEL TRACTOR
    OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL TRACTOR
121507 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S.DE LA INDUSTRIA DEL TRANSPORTE AUTOMOTOR DE CORDOBA
    OBRA SOCIAL DE LA INDUSTRIA DEL TRANSPORTE  AUTOMOTOR DE CORDOBA
121606 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.DE CONDUCTORES DE TRANSPORTE COLECTIVO DE PASAJEROS
    OBRA SOCIAL CONDUCTORES DE TRANSPORTE COLECTIVO DE PASAJEROS
121705 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S.DEL PERSONAL DE LA ACTIVIDAD DEL TURF
    OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD DEL TURF
121804 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.CONDUCTORES DE TAXIS DE CORDOBA
    OBRA SOCIAL CONDUCTORES DE TAXIS DE CORDOBA
121903 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE VAREADORES
    OBRA SOCIAL DE VAREADORES
122005 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S.PARA EL PERSONAL DE LA INDUSTRIA DEL VESTIDO Y AFINES
    OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL VESTIDO
122104 Encrontrado. Tipos: ['1', '2', '3', '4', '7']
    Names:
    O.S.DE VIAJANTES VENDEDORES DE LA REPUBLICA ARGENTINA
    OBRA SOCIAL DE VIAJANTES VENDEDORES DE LA REPUBLICA ARGENTINA. (ANDAR)
122302 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S.DEL PERSONAL DE LA ACTIVIDAD VIAL
    OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD VIAL
122401 Encrontrado. Tipos: ['1', '4', '5', '7']
    Names:
    O.S.DE EMPLEADOS DE LA INDUSTRIA DEL VIDRIO
    OBRA SOCIAL DE  EMPLEADOS DE LA INDUSTRIA DEL VIDRIO
122500 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE LA INDUSTRIA DEL VIDRIO
    OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL VIDRIO
122609 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S.DEL PERSONAL DE LA ACTIVIDAD VITIVINICOLA
    OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD VITIVINICOLA
122807 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE VIGILANCIA Y SEGURIDAD COMERCIAL,INDUSTRIAL E INVESTIGACIONES PRIVADAS DE CORDOBA
    OBRA SOCIAL DEL PERSONAL DE VIGILANCIA Y SEGURIDAD COMERCIAL, INDUSTRIAL E INVESTIGACIONES PRIVADAS DE CORDOBA
122906 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE ESTACIONES DE SERVICIO,GARAGES,PLAYAS DE ESTACIONAMIENTO Y LAVADEROS AUTOMATICOS DE SANTA FE
    OBRA SOCIAL DEL PERSONAL DE ESTACIONES DE SERVICIO, GARAGES, PLAYAS Y LAVADEROS AUTOMATICOS DE LA PROVINCIA DE SANTA FE
123008 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.PARA EL PERSONAL DE ESTACIONES DE SERVICIO,GARAGES,PLAYAS DE ESTACIONAMIENTO,LAVADEROS AUTOMATICOS
        Y GOMERIAS DE LA REPUBLICA ARGENTINA
    OBRA SOCIAL PARA EL PERSONAL DE ESTACIONES DE SERVICIO, GARAGES, PLAYAS DE ESTACIONAMIENTO, LAVADEROS AUTOMATICOS
        Y GOMERIAS DE LA REPUBLICA ARGENTINA
123107 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE TALLERISTAS A DOMICILIO
    OBRA SOCIAL TALLERISTAS A DOMICILIO
123305 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE SOCIEDADES DE AUTORES Y AFINES
    OBRA SOCIAL DEL PERSONAL DE SOCIEDADES DE AUTORES Y AFINES
123404 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.DEL PERSONAL DE PRENSA DE ROSARIO
    OBRA SOCIAL DEL PERSONAL DE PRENSA DE ROSARIO
123503 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DEL PERSONAL DE PRENSA DE TUCUMAN
    OBRA SOCIAL DEL PERSONAL DE PRENSA DE TUCUMAN
123602 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE TRABAJADORES DE PERKINS ARGENTINA S.A.I.C.
    OBRA SOCIAL DE TRABAJADORES DE PERKINS ARGENTINA S.A.I.C
123701 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE PEONES DE TAXIS DE LA CAPITAL FEDERAL
    OBRA SOCIAL DE PEONES DE TAXIS DE LA CAPITAL FEDERAL
123909 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE VENDEDORES AMBULANTES DE LA REPUBLICA ARGENTINA
    OBRA SOCIAL DE VENDEDORES AMBULANTES DE LA REPUBLICA ARGENTINA
124001 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE BOXEADORES AGREMIADOS DE LA REPUBLICA ARGENTINA
    OBRA SOCIAL DE BOXEADORES AGREMIADOS DE LA REPUBLICA ARGENTINA
124506 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE LOS TRABAJADORES DE LA INDUSTRIA DEL GAS
    OBRA SOCIAL DE TRABAJADORES DE LA INDUSTRIA DEL GAS
125103 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE LOS PROFESIONALES UNIVERSITARIOS DEL AGUA Y ENERGIA ELECTRICA
    OBRA SOCIAL DE LOS PROFESIONALES UNIVERSITARIOS DEL AGUA Y LA ENERGIA ELECTRICA
125301 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.FEDERAL NACIONAL DE OBRAS SANITARIAS
    OBRA SOCIAL FEDERAL DE LA FEDERACION NACIONAL DE TRABAJADORES DE OBRAS SANITARIAS
125509 Encrontrado. Tipos: ['1', '4', '5', '7']
    Names:
    O.S.DE LA FEDERACION ARGENTINA DEL TRABAJADOR DE LAS UNIVERSIDADES NACIONALES
    OBRA SOCIAL DE LA FEDERACION ARGENTINA DEL TRABAJADOR  DE LAS UNIVERSIDADES NACIONALES
125707 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S.DEL PERSONAL CIVIL DE LA NACION
    OBRA SOCIAL UNION PERSONAL DE LA UNION DEL  PERSONAL CIVIL DE LA NACION
125905 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.ARBITROS DEPORTIVOS DE LA REPUBLICA ARGENTINA
    OBRA SOCIAL DE ARBITROS DEPORTIVOS DE LA REPUBLICA ARGENTINA
126007 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.FEDERACION GREMIAL INDUSTRIA DE LA CARNE Y SUS DERIVADOS
    OBRA SOCIAL DE LA FEDERACION GREMIAL DEL PERSONAL DE  LA INDUSTRIA DE LA CARNE Y SUS DERIVADOS
126106 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.DE LOS TRABAJADORES DE LA EDUCACION PRIVADA
    OBRA SOCIAL PARA LOS TRABAJADORES DE LA EDUCACION PRIVADA
126304 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    O.S.BANCARIA ARGENTINA
    OBRA SOCIAL SERVICIOS SOCIALES BANCARIOS
126502 Encrontrado. Tipos: ['1', '7']
    Names:
    OS CONFEDERACION DE OBREROS Y EMPLEADOS MUNICIPALES ARGENTINA
    OBRA SOCIAL DE LA CONFEDERACION DE OBREROS Y EMPLEADOS MUNICIPALES  ARGENTINA ( OSCOEMA )
126601 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.PERSONAL DE INDUSTRIAS QUIMICAS Y PETROQUIMICAS ZARATE CAMPANA
    OBRA SOCIAL DEL PERSONAL DE INDUSTRIAS  QUIMICAS Y PETROQUIMICAS DE ZARATE CAMPANA
126700 Encrontrado. Tipos: ['1', '7']
    Names:
    OS DEL PERSONAL DE LA ACTIVIDAD AZUCARERA TUCUMANA
    OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD AZUCARERA TUCUMANA
126809 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    OS DE CONDUCTORES DE REMISES Y AUTOS AL INSTANTE Y AFINES
    OBRA SOCIAL DE CONDUCTORES DE REMISES Y AUTOS AL INSTANTE Y AFINES
126908 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    OBRA SOCIAL DE LOS MEDICOS DE LA CIUDAD DE BUENOS AIRES
    OBRA SOCIAL DE LOS MEDICOS DE LA CIUDAD DE BUENOS AIRES
127000 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S.DE TRABAJADORES DE ESTACIONES DE SERVICIO (OSTES)
    OBRA SOCIAL DE TRABAJADORES DE ESTACIONES DE SERVICIO
127109 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    OS DEL PERSONAL DE LAS TELECOMUNICACIONES SINDICATO BS AS (OSPETELCO)
    OBRA SOCIAL DEL PERSONAL DE TELECOMUNICACIONES SINDICATO BUENOS AIRES
127208 Encrontrado. Tipos: ['1', '7']
    Names:
    OS DE MANDOS MEDIOS DE LAS TELECOMUNICACIONES DE LA RA Y EL MERCOSUR - OSMMEDT
    OBRA SOCIAL DE MANDOS MEDIOS DE TELECOMUNICACIONES EN LA REPUBLICA ARGENTINA Y MERCOSUR
127307 Encrontrado. Tipos: ['1', '4', '5', '7']
    Names:
    OS DE TRABAJADORES VIALES Y AFINES DE LA REPUBLICA ARGENTINA
    OBRA SOCIAL DE LOS TRABAJADORES VIALES Y AFINES DE LA REPUBLICA ARGENTINA
127406 Encrontrado. Tipos: ['1', '2', '3', '7']
    Names:
    OS DE OBREROS Y EMPLEADOS TINTOREROS, SOMBREROS Y LAVADEROS DE LA R.A.
    OBRA SOCIAL DE OBREROS Y EMPLEADOS TINTOREROS SOMBREREROS Y LAVADEROS DE LA REPUBLICA ARGENTINA
127505 Encrontrado. Tipos: ['1', '7']
    Names:
    OS DE LAS ASOCIACIONES DE EMPLEADOS DE FARMACIA (OSADEF)
    OBRA SOCIAL DE  LAS ASOCIACIONES DE EMPLEADOS DE FARMACIA
127604 Encrontrado. Tipos: ['1', '4', '7']
    Names:
    O.S. PARA EL PERSONAL DE OBRAS Y SERVICIOS SANITARIOS
    OBRA SOCIAL DEL PERSONAL DE OBRAS Y SERVICIOS SANITARIOS
127703 Encrontrado. Tipos: ['1', '7']
    Names:
    OS PERSONAL ESTACIONES DE SERVICIO, GARAGES, PLAYAS Y LAVADEROS DE LA PCIA. CHACO
    OBRA SOCIAL PERSONAL ESTACIONES DE SERVICIO,GARAGES,PLAYAS Y LAVADEROS DE LA PROVINCIA DEL CHACO
127802 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    OS DE LUZ Y FUERZA DE LA PATAGONIA
    OBRA SOCIAL DE LUZ Y FUERZA DE LA PATAGONIA
127901 Encrontrado. Tipos: ['1', '5', '7']
    Names:
    OS DE PETROLEROS PRIVADOS
    OBRA SOCIAL DE PETROLEROS PRIVADOS
128003 Encrontrado. Tipos: ['1', '7']
    Names:
    OS DEL PERSONAL DE LA FEDERACION  DE SINDICATOS DE LA INDUSTRIA QUIMICA Y PETROQUIMICA
    OBRA SOCIAL DEL PERSONAL DE LA FEDERACION DE SINDICATOS DE LA INDUSTRIA QUIMICA Y PETROQUIMICA
128102 Encrontrado. Tipos: ['1', '7']
    Names:
    OBRA SOCIAL DE LA UNION DE TRABAJADORES DEL INSSJyP
    OBRA SOCIAL DE LA UNION DE TRABAJADORES DEL INSTITUTO NACIONAL DE SERVICIOS SOCIALES PARA JUBILADOS
        Y PENSIONADOS DE LA REPUBLICA ARGENTINA
128201 Encrontrado. Tipos: ['1', '7']
    Names:
    OBRA SOCIAL DEL SINDICATO UNIC DE RECOLECTORES DE RESIDUOS Y BARRIDO DE CORDOBA
    OBRA SOCIAL DEL SINDICATO UNICO DE RECOLECTORES DE RESIDUOS Y BARRIDO DE CORDOBA
128300 Encrontrado. Tipos: ['1', '7']
    Names:
    OBRA SOCIAL DE PEONES DE TAXI DE ROSARIO
    OBRA SOCIAL PEONES DE TAXIS DE ROSARIO
128409 Encrontrado. Tipos: ['1', '7']
    Names:
    O.S. DEL SINDICATO OBREROS Y EMPLEADOS DE EMPRESAS DE LIMPIEZA, SERVICIOS Y AFINES DE CORDOBA
    OBRA SOCIAL DEL SINDICATO OBREROS Y EMPLEADOS DE EMPRESAS DE LIMPIEZA,SERVICIOS Y AFINES DE CORDOBA
128508 Encrontrado. Tipos: ['1', '2', '3', '7']
    Names:
    OBRA SOCIAL FARMACEUTICOS Y BIOQUIMICOS
    OBRA SOCIAL DE FARMACEUTICOS Y BIOQUIMICOS
128607 Encrontrado. Tipos: ['1', '7']
    Names:
    OBRA SOCIAL DE TRABAJADORES DEL PETROLEO Y GAS PRIVADO DEL CHUBUT
    OBRA SOCIAL DE TRABAJADORES DEL PETROLEO Y GAS PRIVADO DEL CHUBUT
128706 Encrontrado. Tipos: ['1', '7']
    Names:
    OBRA SOCIAL DEL PERSONAL DE DRAGADO Y BALIZAMIENTO
    OBRA SOCIAL DEL PERSONAL DE DRAGADO Y BALIZAMIENTO
128904 Encrontrado. Tipos: ['1', '7']
    Names:
    OBRA SOCIAL DE LOS TRABAJADORES ARGENTINOS DE CENTROS DE CONTACTOS
    OBRA SOCIAL DE LOS TRABAJADORES ARGENTINOS DE CENTROS DE CONTACTOS
129006 Encrontrado. Tipos: ['1', '7']
    Names:
    OBRA SOCIAL DE LA ASOCIACIÓN DEL PERSONAL SUPERIOR DE EPEC
    OBRA SOCIAL DE LA ASOCIACION DEL PERSONAL SUPERIOR DE LA EMPRESA PROVINCIAL DE ENERGIA DE CORDOBA
200400 Encrontrado. Tipos: ['1', '5', '8']
    Names:
    O.S.DE LA EMPRESA NACIONAL DE CORREOS Y TELEGRAFOS S.A.Y DE LAS COMUNICACIONES DE LA REPUBLICA ARGENTINA
    OBRA SOCIAL DEL PERSONAL DE LA EMPRESA NACIONAL DE CORREOS Y TELEGRAFOS S.A. Y DE LAS  COMUNICACIONES DE LA REPULICA ARGENTINA
300704 Encrontrado. Tipos: ['1', '5', '9']
    Names:
    O.S.CERAS JOHNSON
    OBRA SOCIAL CERAS JOHNSON
302106 Encrontrado. Tipos: ['1', '9']
    Names:
    O.S.PARA DIRECTIVOS,TECNICOS Y EMPLEADOS DE JOHN DEERE ARGENTINA
    OBRA SOCIAL PARA DIRECTIVOS, TECNICOS Y EMPLEADOS DE JOHN DEERE ARGENTINA
302809 Encrontrado. Tipos: ['1', '9']
    Names:
    O.S.REFINERIAS DE MAIZ S.A.I.C.F.
    OBRA SOCIAL REFINERIAS DE MAIZ S.A.I.C.F.
303109 Encrontrado. Tipos: ['1', '9']
    Names:
    O.S.SUPERCO
    OBRA SOCIAL SUPERCO
303307 Encrontrado. Tipos: ['1', '4', '9']
    Names:
    O.S.CABOT ARGENTINA
    OBRA SOCIAL CABOT ARGENTINA
303406 Encrontrado. Tipos: ['1', '9']
    Names:
    O.S.DEL PERSONAL DE SHELL-CAPSA
    OBRA SOCIAL DE SHELL ARGENTINA
303703 Encrontrado. Tipos: ['1', '5', '9']
    Names:
    O.S.DEL PERSONAL DE PBBPOLISUR DE BAHIA BLANCA
    OBRA SOCIAL DEL PERSONAL DE PBBPOLISUR  SRL DE  BAHIA BLANCA
303901 Encrontrado. Tipos: ['1', '9']
    Names:
    O.S.FORD ARGENTINA S.A.
    OBRA SOCIAL DE FORD AGENTINA S.C.A
304003 Encrontrado. Tipos: ['1', '9']
    Names:
    O.S.VOLKSWAGEN ARGENTINA S.A.
    OBRA SOCIAL DE VOLKSWAGEN ARGENTINA S.A.
400107 Encrontrado. Tipos: ['1', '5', '10']
    Names:
    O.S.DEL PERSONAL DE DIRECCION DE LAS EMPRESAS DE LA ALIMENTACION Y DEMAS ACTIVIDADES EMPRESARIAS
    OBRA SOCIAL DEL PERSONAL DE DIRECCION DE LAS EMPRESAS DE LA ALIMENTACION Y DEMAS ACTIVIDADES EMPRESARIAS
400206 Encrontrado. Tipos: ['1', '10']
    Names:
    O.S.DEL PERSONAL DE DIRECCION DE LA INDUSTRIA AUTOMOTRIZ ARGENTINA
    OBRA SOCIAL DEL PERSONAL DE DIRECCION DE LA INDUSTRIA AUTOMOTRIZ ARGENTINA
400305 Encrontrado. Tipos: ['1', '10']
    Names:
    O.S.COOPERATIVA LIMITADA DE ASISTENCIA MEDICA,FARMACEUTICA,CREDITO Y CONSUMO DEL PERSONAL SUPERIOR
        DE LA INDUSTRIA DEL CAUCHO Y OTRAS ACTIVIDADES INDU
    OBRA SOCIAL COOPERATIVA LTDA.  DE ASISTENCIA MEDICA Y FARMACEUTICA, SERVICIOS ASISTENCIALES Y TURISMO
        DEL PERSONAL SUPERIOR DE LA INDUSTRIA DEL CAUCHO Y OTRAS ACTIVIDADES INDUSTRIALES
400404 Encrontrado. Tipos: ['1', '4', '5', '10']
    Names:
    O.S.DEL PERSONAL DE DIRECCION DE LA INDUSTRIA CERVECERA Y MALTERA
    OBRA SOCIAL DEL PERSONAL DE DIRECCION DE LA INDUSTRIA CERVECERA Y MALTERA
400503 Encrontrado. Tipos: ['1', '10']
    Names:
    O.S.DEL PERSONAL DE DIRECCION Y JERARQUICO DE LA INDUSTRIA DEL CIGARRILLO
    OBRA SOCIAL DE LA ASOCIACION DEL PERSONAL DE DIRECCION Y JERARQUICO DE LA INDUSTRIA DEL CIGARRILLO
400602 Encrontrado. Tipos: ['1', '10']
    Names:
    O.S.DEL PERSONAL DIRECTIVO DE LA INDUSTRIA DE LA CONSTRUCCION
    OBRA SOCIAL DEL PERSONAL DIRECTIVO DE LA INDUSTRIA DE LA CONSTRUCCION
400701 Encrontrado. Tipos: ['1', '10']
    Names:
    O.S.CAMARA DE LA INDUSTRIA CURTIDORA ARGENTINA
    OBRA SOCIAL PERSONAL DE DIRECCION DE LA INDUSTRIA CURTIDORA ARGENTINA
400800 Encrontrado. Tipos: ['1', '4', '10']
    Names:
    ORGANIZACION DE SERVICIOS DIRECTOS EMPRESARIOS
    OBRA SOCIAL DE EJECUTIVOS Y DEL PERSONAL DE DIRECCION DE EMPRESAS
400909 Encrontrado. Tipos: ['1', '10']
    Names:
    O.S.ACCION SOCIAL DE EMPRESARIOS
    OBRA SOCIAL DEL PERSONAL DE DIRECCION  ACCION SOCIAL DE EMPRESARIOS (A:S:E.)
401001 Encrontrado. Tipos: ['1', '10']
    Names:
    O.S.DEL PERSONAL DE DIRECCION DE LAS EMPRESAS QUE ACTUAN EN FRUTOS DEL PAIS
    OBRA SOCIAL DEL PERSONAL DE DIRECCION DE LAS EMPRESAS QUE ACTUAN EN FRUTOS DEL PAIS
401100 Encrontrado. Tipos: ['1', '10']
    Names:
    O.S.DEL PERSONAL DE DIRECCION ALFREDO FORTABAT
    OBRA SOCIAL DEL PERSONAL DE DIRECCION ALFREDO FORTABAT
401209 Encrontrado. Tipos: ['1', '5', '10']
    Names:
    O.S.DEL PERSONAL DE DIRECCION DE LA INDUSTRIA METALURGICA Y DEMAS ACT. EMPRESARIAS
    OBRA SOCIAL DEL PERSONAL DE DIRECCION DE LA INDUSTRIA METALURGICA  Y DEMAS ACTIVIDADES EMPRESARIAS
401308 Encrontrado. Tipos: ['1', '10']
    Names:
    O.S.PARA EL PERSONAL DE DIRECCION DE LA INDUSTRIA MADERERA
    OBRA SOCIAL PARA EL PERSONAL DE DIRECCION DE LA INDUSTRIA MADERERA
401605 Encrontrado. Tipos: ['1', '4', '10']
    Names:
    O.S.DEL PERSONAL DE DIRECCION DE LA INDUSTRIA PRIVADA DEL PETROLEO
    OBRA SOCIAL DEL PERSONAL DE DIRECCION DE LA INDUSTRIA PRIVADA DEL PETROLEO
401704 Encrontrado. Tipos: ['1', '2', '3', '5', '10']
    Names:
    O.S.EMPRESARIOS,PROFESIONALES Y MONOTRIBUTISTAS
    OBRA SOCIAL  DE EMPRESARIOS, PROFESIONALES Y MONOTRIBUTISTAS
401803 Encrontrado. Tipos: ['1', '10']
    Names:
    O.S.ASOCIACION MUTUAL DEL PERSONAL DE PHILIPS ARGENTINA (AMPAR)
    OBRA SOCIAL ASOCIACION MUTUAL DEL PERSONAL DE PHILIPS ARGENTINA (AMPAR)
401902 Encrontrado. Tipos: ['1', '5', '10']
    Names:
    O.S.DEL PERSONAL DE DIRECCION DE PERFUMERIAS E.W.HOPE
    OBRA SOCIAL DEL PERSONAL DE DIRECCION DE PERFUMERIA E.W. HOPE
402004 Encrontrado. Tipos: ['1', '5', '10']
    Names:
    O.S.DEL PERSONAL DE DIRECCION DE LA SANIDAD LUIS PASTEUR
    OBRA SOCIAL DEL PERSONAL DE DIRECCION DE SANIDAD LUIS PASTEUR
402103 Encrontrado. Tipos: ['1', '5', '10']
    Names:
    O.S.ASOCIACION DEL PERSONAL DE DIRECCION DE LA INDUSTRIA SIDERURGICA
    OBRA SOCIAL ASOCIACION DEL PERSONAL DE DIRECCION DE LA INDUSTRIA SIDERURGICA
402202 Encrontrado. Tipos: ['1', '2', '3', '5', '10']
    Names:
    O.S.MUTUALIDAD INDUSTRIAL TEXTIL ARGENTINA
    OBRA SOCIAL MUTUALIDAD INDUSTRIAL TEXTIL ARGENTINA
402301 Encrontrado. Tipos: ['1', '5', '10']
    Names:
    O.S.ASOCIACION DEL PERSONAL SUPERIOR DE LA ORGANIZACIÓN TECHINT
    OBRA SOCIAL ASOCIACION DEL PERSONAL SUPERIOR DE LA ORGANIZACION TECHINT
402400 Encrontrado. Tipos: ['1', '5', '10']
    Names:
    O.S.DEL PERSONAL DE DIRECCION DE LA INDUSTRIA VITIVINICOLA Y AFINES
    OBRA SOCIAL PARA EL PERSONAL DE DIRECCION DE LA INDUSTRIA VITIVINICOLA Y AFINES
402509 Encrontrado. Tipos: ['1', '4', '10']
    Names:
    OS YPF
    OBRA SOCIAL YPF
402608 Encrontrado. Tipos: ['1', '2', '3', '10']
    Names:
    OS ASOCIACION DE SERVICIOS SOCIALES PARA EMPRESARIOS Y PERSONAL DE DIRECCION DE EMPRESAS DEL
        COMERCIO, SERVICIOS, PRODUCCION, INDUSTRIA Y CIVIL (ASPE)
    OBRA SOCIAL ASOCIACION DE SERVICIOS SOCIALES PARA EMPRESARIOS Y PERSONAL DE DIRECCION DE EMPRESAS DEL
        COMERCIO, SERVICIOS, PRODUCCION, INDUSTRIA Y CIVIL (ASSPE )
402707 Encrontrado. Tipos: ['1', '10']
    Names:
    O.S. DE DIRECCION OSDO
    OBRA SOCIAL DE DIRECCION OSDO
402806 Encrontrado. Tipos: ['1', '10']
    Names:
    OS DE DIRECCION DE LA ACTIVIDAD AEROCOMERCIAL PRIVADA
    OBRA SOCIAL DE DIRECCION DE LA ACTIVIDAD AEROCOMERCIAL  PRIVADA
500807 Encrontrado. Tipos: ['11']
    Names:
    INSTITUTO NACIONAL DE SERVICIOS SOCIALES PARA JUBILADOS Y PENSIONADOS
    INSTITUTO NACIONAL DE SERVICIOS SOCIALES PARA JUBILADOS Y PENSIONADOS
600309 No encontrado en nuestra base de datos
    600309 - ASOCIACION DE OBRAS SOCIALES DE BELLA VISTA
600408 Encrontrado. Tipos: ['1', '12']
    Names:
    ASOCIACION DE OBRAS SOCIALES DE COMODORO RIVADAVIA
    ASOCIACION DE OBRAS SOCIALES DE COMODORO RIVADAVIA
602305 Encrontrado. Tipos: ['1', '5', '12']
    Names:
    ASOCIACION DE OBRAS SOCIALES DE ROSARIO
    ASOCIACION DE OBRAS SOCIALES DE ROSARIO
603100 Encrontrado. Tipos: ['1', '12']
    Names:
    ASOCIACION DE OBRAS SOCIALES DE TRELEW
    ASOCIACION DE OBRAS SOCIALES DE TRELEW
700108 Encrontrado. Tipos: ['1', '18']
    Names:
    O.S.DEL PERSONAL MUNICIPAL DE AVELLANEDA
    OBRA SOCIAL DEL PERSONAL MUNICIPAL DE AVELLANEDA
700801 Encrontrado. Tipos: ['1', '18']
    Names:
    O.S.DEL PERSONAL MUNICIPAL DE LA MATANZA
    OBRA SOCIAL DEL PERSONAL MUNICIPAL DE LA MATANZA
701002 Encrontrado. Tipos: ['1', '4', '18']
    Names:
    O.S.DEL PERSONAL MUNICIPAL DE TRES DE FEBRERO
    OBRA SOCIAL PARA EL  PERSONAL MUNICIPAL DE TRES DE FEBRERO
800501 Encrontrado. Tipos: ['1', '4', '5', '13']
    Names:
    O.S.ACEROS PARANA
    OBRA SOCIAL ACEROS PARANA
900102 Encrontrado. Tipos: ['1', '14', '19']
    Names:
    O.S.DEL PERSONAL DE EMPRESAS FIAT Y EMPRESAS PEUGEOT CITROEN ARG.
    OBRA SOCIAL DEL PERSONAL DE EMPRESAS FIAT Y EMPRESAS PEUGEOT CITROEN ARGENTINA
900300 Encrontrado. Tipos: ['1', '14', '19']
    Names:
    ASOCIACION MUTUAL RURALISTA
    ASOCIACION MUTUAL RURALISTA
900409 Encrontrado. Tipos: ['1', '14', '19']
    Names:
    LA CASA DEL MEDICO MUTUAL
    LA CASA DEL MEDICO MUTUAL
900508 Encrontrado. Tipos: ['1', '14', '19']
    Names:
    CYNTHIOS SALUD S.A.
    CYNTHIOS SALUD S.A.
900607 Encrontrado. Tipos: ['1', '14', '19']
    Names:
    SABER SOCIEDAD ANÖNIMA
    SABER S.A.
900706 Encrontrado. Tipos: ['1', '14', '19']
    Names:
    PRESTADORES SANATORIALES SA
    PRESTADORES SANATORIALES SA
900805 Encrontrado. Tipos: ['1', '14', '19']
    Names:
    SWISS MEDICAL SA
    SWISS MEDICAL S.A.
900904 Encrontrado. Tipos: ['14', '19']
    Names:
    ASOCIACIÓN MUTUAL DE SALUD DE CIUDADELA
    ASOCIACION MUTUAL DE SALUD CIUDADELA
Total: 300, encontrados = 296, no encontrados 2

"""
